
	import javax.swing.JOptionPane;

	/**
	 *
	 * @author l'uniik touti
	 */
	public class Inscription extends javax.swing.JFrame {

	    /**
	     * Creates new form Inscription
	     */
	    public Inscription() {
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        jLabel1 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        log1 = new javax.swing.JTextField();
	        jLabel3 = new javax.swing.JLabel();
	        mdp1 = new javax.swing.JPasswordField();
	        jLabel4 = new javax.swing.JLabel();
	        mdp2 = new javax.swing.JPasswordField();
	        jButton1 = new javax.swing.JButton();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
	        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
	        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
	        jLabel1.setText("INSCRIPTION");

	        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
	        jLabel2.setText("Entree votre login");

	        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
	        jLabel3.setText("Entree votre mot de passe");

	        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
	        jLabel4.setText("Confirmer mot de passe");

	        jButton1.setBackground(new java.awt.Color(0, 102, 102));
	        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
	        jButton1.setForeground(new java.awt.Color(0, 51, 51));
	        jButton1.setText("Validation");
	        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
	            public void mouseClicked(java.awt.event.MouseEvent evt) {
	                Enregistrement(evt);
	            }
	        });

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addGap(152, 152, 152)
	                        .addComponent(jLabel2))
	                    .addGroup(layout.createSequentialGroup()
	                        .addGap(113, 113, 113)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addGroup(layout.createSequentialGroup()
	                                .addGap(10, 10, 10)
	                                .addComponent(jLabel3))
	                            .addComponent(mdp1)
	                            .addComponent(log1)
	                            .addComponent(mdp2)))
	                    .addGroup(layout.createSequentialGroup()
	                        .addGap(136, 136, 136)
	                        .addComponent(jLabel4))
	                    .addGroup(layout.createSequentialGroup()
	                        .addGap(156, 156, 156)
	                        .addComponent(jButton1)))
	                .addContainerGap(116, Short.MAX_VALUE))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addComponent(jLabel1)
	                .addGap(18, 18, 18)
	                .addComponent(jLabel2)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(log1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(mdp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(jLabel4)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addComponent(mdp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(18, 18, 18)
	                .addComponent(jButton1)
	                .addGap(0, 70, Short.MAX_VALUE))
	        );

	        pack();
	    }// </editor-fold>                        
//cette methode permet a l'utilisateur de s'inscrire et l'enregiste dans notre base de données
	    private void Enregistrement(java.awt.event.MouseEvent evt) {                                
	        // TODO add your handling code here:
	        String login=log1.getText().toString();
	        String mdp=mdp1.getText().toString();
	        String mdp3=mdp2.getText().toString();
	       if(mdp1==mdp2){
	            ConnexionBase c=new ConnexionBase();
	            c.insert(login, mdp);
	            Connexion con=new Connexion();
	            con.setVisible(true);
	       }
	        else 
	           JOptionPane.showMessageDialog(rootPane,"les deux mot de passe ne sont pas conforme");
	            
	    }                               

	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new Inscription().setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify                     
	    private javax.swing.JButton jButton1;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JTextField log1;
	    private javax.swing.JPasswordField mdp1;
	    private javax.swing.JPasswordField mdp2;
	    // End of variables declaration                   
	}


